In [27]:
import numpy as np

baseball=[[180,78.4], [215,102.7], [210,98.5],[188,75.2]]
#create a 2D numpy array from baseball: np_baseball
np_baseball=np.array(baseball)
#print out the type of np_baseball
print(type(np_baseball))
# Print out the shape of np_baseball
#baseball=np.baseballl([1,2,3])
print(np_baseball.shape)
#create a 2D numpy array from baseball:np_baseball
# Print out the shape of np_baseball
print(np_baseball.shape)
np_baseball=np.array(baseball)
#print out the 50th row of np_baseball
print(np_baseball[0])
# Select the entire second column of np_baseball: np_weight_lb
np_weight_lb=np_baseball[:,1]
#Print out the height of 124th player
print(np_baseball[:0])
np_baseball=np.array(baseball)
#print out the addition of np_baseball + updated 
updated=np.array([[0.0, 0.0], [0.0,0.0],[0.0,0.0],[0.0,0.0]])
np_baseball_updated =np_baseball+ updated
print(np_baseball_updated)
#create numpy array: conversion
conversion=np.array([0.0254, 0.452592])
#print out product of np_baseball *conversion
np_baseball_metric=np_baseball * conversion
print(np_baseball_metric)
# create np_height_in from np_baseball
np_height_in=np_baseball[:,0]
#print out the mean of np_height_in
print(np.mean(np_height_in))
#print out the median of np_height_in
print(np.median(np_height_in))
avg= np.mean(np_baseball[:,0])
# Print median height
med= np.median(np_baseball[:,0])
print("Median, " +str(med))

# Print out the standard deviation on height
stdev= np.std(np_baseball[:,0])
print("Standard Deviation: " +str(stdev))

# Print out correlation between first and second column
corr= np.corrcoef(np_baseball[:,0], np_baseball[:,1])
print(corr)

<class 'numpy.ndarray'>
(4, 2)
(4, 2)
[180.   78.4]
[]
[[180.   78.4]
 [215.  102.7]
 [210.   98.5]
 [188.   75.2]]
[[ 4.572     35.4832128]
 [ 5.461     46.4811984]
 [ 5.334     44.580312 ]
 [ 4.7752    34.0349184]]
198.25
199.0
Median, 199.0
Standard Deviation: 14.635146053251399
[[1.         0.95865738]
 [0.95865738 1.        ]]
